-- Allow two-level CMS appraisal flow:
-- PENDING_REVIEW -> PENDING_APPROVAL -> AWAITING_BORROWER_APPROVAL.
ALTER TABLE loan_requests
  MODIFY COLUMN status ENUM(
    'PENDING_REVIEW',
    'PENDING_APPROVAL',
    'AWAITING_BORROWER_APPROVAL',
    'ACTIVE',
    'FUNDED',
    'REPAYING',
    'COMPLETED',
    'DEFAULTED',
    'REJECTED',
    'CANCELLED'
  ) NOT NULL DEFAULT 'PENDING_REVIEW';
