-- V42: Sản phẩm gọi vốn HKD/DN theo bộ quy định sản phẩm kinh doanh.
-- Chỉ seed/update dữ liệu cấu hình sản phẩm, không tác động dữ liệu hồ sơ gọi vốn.

INSERT INTO loan_products
  (id, code, name, category, product_group, profession_bound, description,
   min_amount, max_amount, available_terms, max_interest_rate, late_fee_rate,
   interest_penalty_rate, early_settlement_fee_rate, early_settlement_free_ratio,
   early_settlement_min_fee, repayment_method, image_url, is_active, is_deleted, sort_order)
VALUES
  ('a7c64c93-3817-4250-b9b2-3b7a2fa46112',
   'BUSINESS_HOUSEHOLD',
   'Gọi vốn hộ kinh doanh cá thể',
   'BUSINESS',
   4,
   0,
   'Bổ sung vốn lưu động, thương vụ ngắn hạn hoặc mở rộng cơ sở kinh doanh cho hộ kinh doanh. Thẩm định dựa trên đăng ký kinh doanh, doanh thu, chi phí, dòng tiền và phương án sử dụng vốn.',
   10000000.00,
   2000000000.00,
   '1,3,6,9,12,18,24,36,60',
   NULL,
   150.00,
   10.00,
   5.00,
   0.6667,
   500000.00,
   'INTEREST_MONTHLY_PRINCIPAL_QUARTERLY',
   'https://service.vnfite.com.vn/static-file//images/loan/image/giaovien.png',
   1,
   0,
   18),

  ('1f686f7d-8570-474a-9d29-614948b4cb11',
   'BUSINESS_ONLINE_SHOP',
   'Gọi vốn shop kinh doanh online',
   'BUSINESS',
   4,
   0,
   'Bổ sung vốn ngắn hạn cho shop kinh doanh online trên sàn thương mại điện tử hoặc kênh bán hàng số. Thẩm định doanh thu tối thiểu 03 tháng, sao kê ví/sàn, uy tín gian hàng, nhà cung cấp và phương án marketing online.',
   10000000.00,
   500000000.00,
   '1,2,3',
   NULL,
   150.00,
   10.00,
   5.00,
   0.6667,
   500000.00,
   'INTEREST_MONTHLY_PRINCIPAL_QUARTERLY',
   'https://service.vnfite.com.vn/static-file//images/loan/image/giaovien.png',
   1,
   0,
   19),

  ('556c1dbe-a690-49c6-87c8-590065e4ea3e',
   'ENTERPRISE_OVERDRAFT',
   'Gọi vốn thấu chi doanh nghiệp',
   'ENTERPRISE',
   4,
   0,
   'Hạn mức vốn ngắn hạn cho doanh nghiệp chi trả chi phí thường xuyên, tiền hàng, dịch vụ, tiền lương và các chi phí hợp pháp phục vụ hoạt động kinh doanh. Yêu cầu doanh nghiệp hoạt động tối thiểu 12 tháng và đạt điều kiện lịch sử tín dụng.',
   10000000.00,
   100000000.00,
   '1,3,6,12',
   NULL,
   150.00,
   10.00,
   3.00,
   1.0000,
   0.00,
   'INTEREST_MONTHLY_PRINCIPAL_QUARTERLY',
   'https://service.vnfite.com.vn/static-file//images/loan/image/giaovien.png',
   1,
   0,
   20)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  category = VALUES(category),
  product_group = VALUES(product_group),
  profession_bound = VALUES(profession_bound),
  description = VALUES(description),
  min_amount = VALUES(min_amount),
  max_amount = VALUES(max_amount),
  available_terms = VALUES(available_terms),
  max_interest_rate = VALUES(max_interest_rate),
  late_fee_rate = VALUES(late_fee_rate),
  interest_penalty_rate = VALUES(interest_penalty_rate),
  early_settlement_fee_rate = VALUES(early_settlement_fee_rate),
  early_settlement_free_ratio = VALUES(early_settlement_free_ratio),
  early_settlement_min_fee = VALUES(early_settlement_min_fee),
  repayment_method = VALUES(repayment_method),
  image_url = VALUES(image_url),
  is_active = VALUES(is_active),
  is_deleted = VALUES(is_deleted),
  sort_order = VALUES(sort_order);

-- Nếu trước đó có sản phẩm DN tạo tay nhưng gán nhầm nhóm 2, đưa về Nhóm 4 theo QĐ-LSGV.
UPDATE loan_products
SET product_group = 4
WHERE category IN ('BUSINESS', 'ENTERPRISE')
  AND is_deleted = 0;
