-- Bank catalog seeded from VNF_ACCOUNT_MANAGEMENT.tbl_bank_information
CREATE TABLE IF NOT EXISTS bank_catalog (
    id          VARCHAR(36)  NOT NULL PRIMARY KEY,
    bank_code   VARCHAR(50)  NOT NULL UNIQUE,
    bank_name   VARCHAR(255) NOT NULL,
    bank_short_name VARCHAR(100) NOT NULL,
    icon        VARCHAR(255),
    is_deleted  TINYINT(1)   NOT NULL DEFAULT 0,
    created_at  DATETIME     DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO bank_catalog (id, bank_code, bank_name, bank_short_name, icon) VALUES
(UUID(), 'ABBANK', 'An Bình (ABBANK)', 'ABBank', '/images/icon/transfer/bank/3.png'),
(UUID(), 'ACB', 'Á Châu (ACB)', 'ACB', '/images/icon/transfer/bank/41.png'),
(UUID(), 'VBA', 'Nông nghiệp và Phát triển nông thôn (VBA)', 'Agribank', '/images/icon/transfer/bank/32.png'),
(UUID(), 'ANZ', 'TNHH MTV ANZ Việt Nam (ANZ)', 'ANZ', '/images/icon/transfer/bank/42.png'),
(UUID(), 'BAB', 'Bắc Á (NASB)', 'Bac A', '/images/icon/transfer/bank/30.png'),
(UUID(), 'BANGKOK', 'Bangkok Đại chúng TNHH (BANGKOK)', 'BANGKOK', '/images/icon/transfer/bank/43.png'),
(UUID(), 'BVB', 'Bảo Việt (BVB)', 'BaoViet Bank', '/images/icon/transfer/bank/17.png'),
(UUID(), 'BIDC', 'DT-PT CAMPUCHIA (BIDC)', 'BIDC', '/images/icon/transfer/bank/47.png'),
(UUID(), 'BIDV', 'Đầu tư và phát triển (BIDV)', 'BIDV Bank', '/images/icon/transfer/bank/20.png'),
(UUID(), 'BNP_PARIBAS', 'BNP PARIBAS (BNP PARIBAS)', 'BNP PARIBAS', '/images/icon/transfer/bank/48.png'),
(UUID(), 'Busan', 'Busan (Busan)', 'Busan', '/images/icon/transfer/bank/49.png'),
(UUID(), 'CAKE', 'Ngân hàng số CAKE by VPBank', 'CAKE', '/images/icon/transfer/bank/102.png'),
(UUID(), 'CBB', 'Xây dựng Việt Nam (TRUSTBANK)', 'CBB', '/images/icon/transfer/bank/84.png'),
(UUID(), 'CCB', 'Xây dựng Trung Quốc (CCB)', 'CCB', '/images/icon/transfer/bank/50.png'),
(UUID(), 'CCF', 'Hợp tác xã Việt Nam (CCF)', 'CCF', '/images/icon/transfer/bank/51.png'),
(UUID(), 'CHINA', 'Trung Quốc (CHINA)', 'CHINA', '/images/icon/transfer/bank/44.png'),
(UUID(), 'CHINATRUST', 'TNHH CTBC (CHINATRUST)', 'CHINATRUST', '/images/icon/transfer/bank/52.png'),
(UUID(), 'CHINESE', 'OVERSEA - CHINESE BANKING CORP (CHINESE)', 'CHINESE', '/images/icon/transfer/bank/76.png'),
(UUID(), 'CIMB', 'TNHH MTV CIMB Việt Nam (CIMB)', 'CIMB', '/images/icon/transfer/bank/53.png'),
(UUID(), 'CITIBANK', 'Citibank Việt Nam (CITIBANK)', 'CITIBANK', '/images/icon/transfer/bank/54.png'),
(UUID(), 'CITIBANKHCM', 'Citibank TP.Hồ Chí Minh (CITIBANK)', 'CITIBANK HCM', '/images/icon/transfer/bank/100.png'),
(UUID(), 'COMERCIAL', 'FIRST COMMERCIAL BANK (COMERCIAL)', 'COMERCIAL', '/images/icon/transfer/bank/60.png'),
(UUID(), 'COMMONWEALTH', 'COMMONWEALTH BANK (COMMONWEALTH)', 'COMMONWEALTH', '/images/icon/transfer/bank/55.png'),
(UUID(), 'COMMUNICATION', 'BANK OF COMMUNICATIONS (COMMUNICATION)', 'COMMUNICATION', '/images/icon/transfer/bank/45.png'),
(UUID(), 'CSXH', 'Chính sách Xã hội (CSXH)', 'CSXH', '/images/icon/transfer/bank/56.png'),
(UUID(), 'DBS', 'DBS - chi nhánh Thành phố Hồ Chí Minh', 'DBS', '/images/icon/transfer/bank/57.png'),
(UUID(), 'DEUTSCHE', 'DEUTSCHE BANK AG (DEUTSCHE)', 'DEUTSCHE', '/images/icon/transfer/bank/58.png'),
(UUID(), 'DAB', 'Đông Á (DAB)', 'DongABank', '/images/icon/transfer/bank/29.png'),
(UUID(), 'ESUN', 'Thương Mại TNHH E.SUN Dong Nai (ESUN)', 'ESUN', '/images/icon/transfer/bank/59.png'),
(UUID(), 'EIB', 'Xuất nhập khẩu (EIB)', 'Exim Bank', '/images/icon/transfer/bank/6.png'),
(UUID(), 'GPB', 'Dầu khí toàn cầu (GPB)', 'GP Bank', '/images/icon/transfer/bank/12.png'),
(UUID(), 'HANA', 'HANA BANK (HANA)', 'HANA', '/images/icon/transfer/bank/62.png'),
(UUID(), 'HDB', 'Phát triển nhà TP HCM (HDB)', 'HD Bank', '/images/icon/transfer/bank/14.png'),
(UUID(), 'HLB', 'TNHH MTV Hong Leong VN (HLB)', 'Hongleong', '/images/icon/transfer/bank/13.png'),
(UUID(), 'HSBC', 'TNHH MTV HSBC Việt Nam (HSBC)', 'HSBC', '/images/icon/transfer/bank/63.png'),
(UUID(), 'HUA_NAN', 'HUA NAN COMMERCIAL BANK (HUA NAN)', 'HUA NAN', '/images/icon/transfer/bank/64.png'),
(UUID(), 'IBK', 'INDUSTRIAL BANK OF KOREA (IBK)', 'IBK', '/images/icon/transfer/bank/65.png'),
(UUID(), 'ICBC', 'Công thương Trung Quốc (ICBC)', 'ICBC', '/images/icon/transfer/bank/66.png'),
(UUID(), 'INDIA', 'Ấn Độ (INDIA)', 'INDIA', '/images/icon/transfer/bank/46.png'),
(UUID(), 'IVB', 'Indovina (IVB)', 'Indovina Bank', '/images/icon/transfer/bank/90.png'),
(UUID(), 'KLB', 'Kiên Long (KLB)', 'KienlongBank', '/images/icon/transfer/bank/36.png'),
(UUID(), 'KBHN', 'KOOKMIN Hà Nội (KOOKMIN)', 'KOOKMIN HN', '/images/icon/transfer/bank/68.png'),
(UUID(), 'KBHCM', 'KOOKMIN TP.HCM (KOOKMIN)', 'KOOKMIN HCM', '/images/icon/transfer/bank/68.png'),
(UUID(), 'KOREA', 'KEB HANA (KOREA)', 'KOREA', '/images/icon/transfer/bank/40.png'),
(UUID(), 'LPB', 'Bưu điện Liên Việt (LPB)', 'LienViet Bank', '/images/icon/transfer/bank/28.png'),
(UUID(), 'MALAYAN', 'Malayan Banking Berhad (MALAYAN)', 'MALAYAN', '/images/icon/transfer/bank/69.png'),
(UUID(), 'MSB', 'Hàng hải (MSB)', 'Maritime Bank', '/images/icon/transfer/bank/7.png'),
(UUID(), 'MAYBANK', 'May Bank (MAYBANK)', 'MAYBANK', '/images/icon/transfer/bank/70.png'),
(UUID(), 'MB', 'Quân đội (MB)', 'MB Bank', '/images/icon/transfer/bank/22.png'),
(UUID(), 'MCB', 'JPMORGAN CHASE (MCB)', 'MCB', '/images/icon/transfer/bank/67.png'),
(UUID(), 'MEGA', 'MEGA ICBC (MEGA)', 'MEGA', '/images/icon/transfer/bank/71.png'),
(UUID(), 'MHB', 'Phát triển nhà Đồng bằng sông Cửu Long (MHB)', 'MHB', '/images/icon/transfer/bank/15.png'),
(UUID(), 'MIZUHOHCM', 'MIZUHO BANK TP HO CHI MINH (MIZUHO)', 'MIZUHO HCM', '/images/icon/transfer/bank/92.png'),
(UUID(), 'MIZUHOHN', 'MIZUHO BANK HA NOI (MIZUHO)', 'MIZUHO HN', '/images/icon/transfer/bank/72.png'),
(UUID(), 'NAB', 'Nam Á (NAMABANK)', 'NAB', '/images/icon/transfer/bank/89.png'),
(UUID(), 'NATIXIS', 'BPCE IOM (NATIXIS)', 'NATIXIS', '/images/icon/transfer/bank/73.png'),
(UUID(), 'NHB_HN', 'NongHyup (Nong Hyup)', 'NHB HN', '/images/icon/transfer/bank/75.png'),
(UUID(), 'OceanBank', 'Đại Dương (OJB)', 'Ocean Bank', '/images/icon/transfer/bank/16.png'),
(UUID(), 'PGB', 'Xăng dầu Petrolimex (PGB)', 'PG Bank', '/images/icon/transfer/bank/37.png'),
(UUID(), 'OCB', 'Phương Đông (OCB)', 'Phuongdong bank', '/images/icon/transfer/bank/24.png'),
(UUID(), 'PVCB', 'Đại chúng Việt Nam (PVC)', 'PVcomBank', '/images/icon/transfer/bank/38.png'),
(UUID(), 'NCB', 'Quốc Dân (NCB)', 'Quoc dan Bank', '/images/icon/transfer/bank/19.png'),
(UUID(), 'STB', 'Sacombank (STB)', 'Sacombank', '/images/icon/transfer/bank/91.png'),
(UUID(), 'SCB', 'Sài Gòn (SCB)', 'SaiGon Bank', '/images/icon/transfer/bank/27.png'),
(UUID(), 'SGICB', 'Sài Gòn Công thương (SGB)', 'Saigonbank', '/images/icon/transfer/bank/33.png'),
(UUID(), 'SEAB', 'Đông Nam Á (SEAB)', 'Sea Bank', '/images/icon/transfer/bank/26.png'),
(UUID(), 'SHANGHAI', 'The Shanghai Commercial & Savings (SHANGHAI)', 'SHANGHAI', '/images/icon/transfer/bank/74.png'),
(UUID(), 'SHB', 'Sài Gòn Hà Nội (SHB)', 'SHB', '/images/icon/transfer/bank/10.png'),
(UUID(), 'SHBVN', 'MTV Shinhan Việt Nam (SHBVN)', 'Shinhan Viet Nam', '/images/icon/transfer/bank/31.png'),
(UUID(), 'SIAM', 'THE SIAM COMMERCIAL BANK PUBLIC (SIAM)', 'SIAM', '/images/icon/transfer/bank/77.png'),
(UUID(), 'SinoPac', 'SinoPac (FAR EAST NATIONAL BANK) (SinoPac)', 'SinoPac', '/images/icon/transfer/bank/78.png'),
(UUID(), 'SMBC', 'SUMITOMO MITSUI BANKING CORPORATION (SMBC)', 'SMBC', '/images/icon/transfer/bank/79.png'),
(UUID(), 'SCVN', 'STANDARD CHARTERED Việt Nam (STANDARDCHARTERED)', 'STANDARDCHARTERED', '/images/icon/transfer/bank/80.png'),
(UUID(), 'TAIPEI', 'Taipei Fubon (TAIPEI)', 'TAIPEI', '/images/icon/transfer/bank/82.png'),
(UUID(), 'TCB', 'Kỹ Thương (TCB)', 'Techcom Bank', '/images/icon/transfer/bank/1.png'),
(UUID(), 'TPB', 'Tiên Phong (TPB)', 'Tien Phong Bank', '/images/icon/transfer/bank/11.png'),
(UUID(), 'TokyoMitsubishi', 'Ngân hàng BANK OF TOKYO MITSUBISHI UFJ', 'TokyoMitsubishi', '/images/icon/transfer/bank/83.png'),
(UUID(), 'Ubank', 'Ngân hàng số Ubank by VPBank', 'UBANK', '/images/icon/transfer/bank/104.png'),
(UUID(), 'UMEE', 'Ngân hàng số UMEE by Kienlongbank', 'UMEE', '/images/icon/transfer/bank/103.png'),
(UUID(), 'UOB', 'United Overseas Bank Việt Nam (UOB)', 'UOB', '/images/icon/transfer/bank/85.png'),
(UUID(), 'VCB', 'Ngoại thương Việt Nam (VCB)', 'VCB', '/images/icon/transfer/bank/86.png'),
(UUID(), 'VDB', 'Phát triển Việt Nam (VDB)', 'VDB', '/images/icon/transfer/bank/87.png'),
(UUID(), 'VIB', 'Quốc tế (VIB)', 'VIB bank', '/images/icon/transfer/bank/5.png'),
(UUID(), 'PBVN', 'Liên doanh VID Public Bank (VID)', 'VID Bank', '/images/icon/transfer/bank/18.png'),
(UUID(), 'VAB', 'Việt Á (VAB)', 'VietA Bank', '/images/icon/transfer/bank/23.png'),
(UUID(), 'VIETBANK', 'Việt Nam Thương tín (VIETBANK)', 'VietBank', '/images/icon/transfer/bank/34.png'),
(UUID(), 'VCCB', 'Bản Việt (VCCB)', 'Vietcapital Bank', '/images/icon/transfer/bank/35.png'),
(UUID(), 'ICB', 'Công Thương Việt Nam (VIETINBANK)', 'Vietin bank', '/images/icon/transfer/bank/25.png'),
(UUID(), 'VPB', 'Việt Nam Thinh Vượng (VPB)', 'VP Bank', '/images/icon/transfer/bank/21.png'),
(UUID(), 'VRB', 'Liên Doanh Việt Nga (VRB)', 'VRB', '/images/icon/transfer/bank/39.png'),
(UUID(), 'WVN', 'Woori Việt Nam (Woori)', 'Woori', '/images/icon/transfer/bank/88.png')
ON DUPLICATE KEY UPDATE
    bank_name = VALUES(bank_name),
    bank_short_name = VALUES(bank_short_name),
    icon = VALUES(icon);
